# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '42 4 5,20 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3"]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install test dependencies
      run: python -m pip install jax scipy matplotlib scikit-learn "numpy<2" setuptools scipy flake8 pycodestyle pydocstyle pytest hypothesis coverage coverage_lcov[extras] toml 

    - name: Install package
      run: python -m pip install .

    - name: Lint with flake8
      run: flake8 wNMFx/*.py

    - name: Check code style
      run: pycodestyle wNMFx/*.py

    - name: Check doc style
      run: pydocstyle wNMFx/*.py

    - name: Test with pytest
      run: PYTHONPATH=. python3 -m coverage run -a -m pytest

    - name: Install
      run: python3 -m pip install .

    - name: Convert coverage output to lcov for coveralls
      run: |
        coverage-lcov
        # make paths relative
        sed -i s,$PWD/,,g lcov.info
    - name: prepare coveralls partial upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: lcov.info
        flag-name: run-${{ matrix.python-version }}
        parallel: true

  finish:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
        carryforward: "run-1,run-2"
